name: Run

on:
  push:
    paths:
      - src/**
      - .github/workflows/run.yml

  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "run"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Run TypeScript code
        run: npm run start

      - name: Push to GitHub
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update ($(date +'%Y-%m-%dT%H:%M:%S'))" || exit 0
          git push

  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 9
